# Generated by Django 5.0.1 on 2024-02-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='originals',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='topratedmovie',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
